### ISSUE TITLE
Collapsible not expanding after collapsing

### ISSUE THREAD

**Issue by terreb** [oblador/react-native-collapsible#234] opened 2018-08-30 10:31 UTC
I have TouchableOpacity inside Collapsible component. It registers tap when Collapsible is expanded, but when collapsed TouchableOpacity doesn't register tap and thus I'm unable to expand the view back. Here is my component:

```
const HEADER_HEIGHT = 50

export class CollapsibleView extends PureComponent<Props, State> {

    constructor( props: Props ) {
        super( props )
        this.state = {
            expanded: true,
        }
    }

    render() {
        const { children, onToggle, openHeaderTitle, closeHeaderTitle } = this.props
        const { expanded } = this.state

        const Header = () =>
            <TouchableOpacity
                style={[
                    styles.hContainer,
                    styles.fullWidth,
                    { height: HEADER_HEIGHT, justifyContent: "center", alignItems: "center" }
                    ]}
                onPress={() => {
                    this.setState( { expanded: !expanded } )
                    console.log(this.state)
                    if ( typeof onToggle === 'function' ) onToggle( this.state.expanded )
                }}

            >
                {
                    !expanded ?
                        openHeaderTitle && <Text style={{marginRight: 8 }}>{openHeaderTitle}</Text> :
                        closeHeaderTitle && <Text style={{marginRight: 8 }}>{closeHeaderTitle}</Text>
                }
                {
                    expanded
                        ? <Icon
                            style={{ fontSize: 20, color: COLOR_PRIMARY, paddingBottom: 5 }}
                            type="FontAwesome"
                            name="caret-up"
                        />
                        : <Icon
                            style={{ fontSize: 20, color: COLOR_PRIMARY, paddingBottom: 5 }}
                            type="FontAwesome"
                            name="caret-down"
                        />
                }
            </TouchableOpacity>


        return (
            <Collapsible
                collapsed={!this.state.expanded}
                collapsedHeight={HEADER_HEIGHT}
                align="top"
            >
                <View>
                    <Header />
                    {children}
                </View>
            </Collapsible>
        )
    }
} 
```

Is it me doing something wrong or is it a bug?

**Comment by iRoachie** [comment] 2018-09-28 04:56
Can you create this example on https://snack.expo.io?

**Comment by jamesjara** [comment] 2018-09-28 17:12
Having the same issue, and the problem is @iRoachie because the open/close action is inside the `Collapsible` component, so when we collapse, the `Collapsible` component disable somehow(haven't check the code) so we can click in the component to toggle the collapsible

**Comment by jzabala** [comment] 2018-10-05 13:44
Hi @terreb and @jamesjara I think that is an intended behavior. As you can see the pointerEvents are disable in the view when it is collapsed:

https://github.com/oblador/react-native-collapsible/blob/082c77bde71c608e20496ac2cdbed3aaaa2fe54c/Collapsible.js#L199

**Comment by iRoachie** [comment] 2018-10-07 15:02
@jzabala Should be fixed by https://github.com/oblador/react-native-collapsible/commit/8222cf4d93d8542209d755b8e447a67d8b7fd1e0

**Comment by iRoachie** [comment] 2018-10-07 15:28
[v1.2.0](https://github.com/oblador/react-native-collapsible/releases/tag/v1.2.0) Adds prop for overriding pointerEvents

**Closed by iRoachie** 2018-10-07 15:28 UTC
Labels: fixed-next-release, help wanted
