### ISSUE TITLE
isMounted is deprecated

### ISSUE THREAD

**Issue by markentingh** [oblador/react-native-collapsible#212] opened 2018-06-25 17:30 UTC
After importing & using this component in my React Native project (0.55.4), I get a warning message upon loading:

> Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

The warning appears whenever I change the `collapsed` prop to `true` as well.

**Comment by iRoachie** [comment] 2018-06-25 17:31
Duplicate of #162

**Comment by markentingh** [comment] 2018-06-25 17:32
Cool, I did search for "isMounted" before posting my issue, thanks for such a quick response

**Closed by iRoachie** 2018-06-25 17:31 UTC

**Comment by iRoachie** [comment] 2018-06-25 17:32
No problem, haven't gotten around to looking over the PR as yet.

**Comment by markentingh** [comment] 2018-06-25 17:34
I believe in you :)
