### ISSUE TITLE
Is it possible to open more than one accordion simultaneously?

### ISSUE THREAD

**Issue by okayu8** [oblador/react-native-collapsible#231] opened 2018-08-23 02:31 UTC
By default, one accordion is expanded, but when you expand another accordion, the original accordion will close.
Is it possible to open more than one accordion at the same time?

I did not understand how to allow more than one even after checking properties etc.
If possible, can you tell me which property to use?

**Comment by iRoachie** [comment] 2018-08-23 02:32
Duplicate of #187

**Closed by iRoachie** 2018-08-23 02:32 UTC
