### ISSUE TITLE
react-native-collapsible/Accordion has no exported member 'Accordion'

### ISSUE THREAD

**Issue by parthv21** [oblador/react-native-collapsible#294] opened 2019-07-02 04:18 UTC
Again opening this issue as the previous 2 issues didn't provide any solution. 

This is the dependency in my package.json:

> "react-native-collapsible": "1.4.0"

And I keep getting this error: 

<img width="983" alt="Screen Shot 2019-07-02 at 9 41 20 AM" src="https://user-images.githubusercontent.com/17941287/60482195-2de90800-9cae-11e9-9fdc-14dfff47da6f.png">

I noticed that VSCode can't even index all the contents on the package.

<img width="1017" alt="Screen Shot 2019-07-02 at 9 47 14 AM" src="https://user-images.githubusercontent.com/17941287/60482272-62f55a80-9cae-11e9-9a4a-7c31a5cbadb3.png">

How do I fix this? Or what was the latest version in which this problem was fixed?

Thanks.

**Comment by iRoachie** [comment] 2019-07-02 04:19
Duplicate of #255

**Closed by iRoachie** 2019-07-02 04:19 UTC
