### ISSUE TITLE
onPress inside renderHeader and renderContent throws an error

### ISSUE THREAD

**Issue by mykelaballe** [oblador/react-native-collapsible#58] opened 2016-11-30 18:57 UTC
RN: 0.32
react-native-collapsible: 0.7.0

I have TouchableOpacity inside my renderHeader and renderContent which has an onPress. But when clicking it, it throws an error.

![image](https://cloud.githubusercontent.com/assets/22584900/20766547/d19da20a-b771-11e6-8e8b-4f7f49c116f0.png)

**Comment by thundenilla** [comment] 2017-01-09 02:17
@mykelaballe did you manage to solve it? im stuck in the same situation.

**Comment by Lorezz** [comment] 2017-04-20 10:59
same problem here

**Comment by oblador** [comment] 2017-04-20 20:09
@mykelaballe Have you tried upgrading your version of React Native?

**Comment by barbarossusuz** [comment] 2017-05-30 07:14
same here for this issue, any fix?

**Comment by iRoachie** [comment] 2017-07-21 17:00
@barbarossusuz This problem still occurs?

**Comment by jeanverster** [comment] 2017-08-07 08:53
@iRoachie I can confirm this problem is still happening. 

RN: 0.45.1

Here's my code: 

```_renderContent (section) {
    if (section.children.length !== 0) {
      return section.children.map((store, index) => {
        return (
          <TouchableHighlight onPress={() => this._handlePress(store)} key={index} style={styles.storeRow}>
            <Text style={styles.storeText}>{store.name.toUpperCase()}</Text>
          </TouchableHighlight>
        )
      })
    } else {
      return section.store.map((store, index) => {
        return (
          <TouchableHighlight onPress={() => { }} key={index} style={styles.storeRow}>
            <Text style={styles.storeText}>{store.name.toUpperCase()}</Text>
          </TouchableHighlight>
        )
      })
    }
  }```

Then handlePress:

```_handlePress = (store) => {
    this.props.navigation.navigate('StoreDetailScreen', {store})
  }```

I get "this.handlePress is not a function"

Any ideas as to how to solve this??

**Comment by rdoyle975** [comment] 2017-08-09 17:58
@jeanverster I don't know if it's the right way to fix this but I fixed the problem by inserting my function inside _renderContent (or _renderHeader). So it would look like this:

```
_handlePress = (store) => {
    this.props.navigation.navigate('StoreDetailScreen', {store})
  }

_renderContent (section) {
    if (section.children.length !== 0) {
      return section.children.map((store, index) => {
        return (
          <TouchableHighlight onPress={() => _handlePress(store)} key={index} style={styles.storeRow}>
            <Text style={styles.storeText}>{store.name.toUpperCase()}</Text>
          </TouchableHighlight>
        )
      })
    } else {
      return section.store.map((store, index) => {
        return (
          <TouchableHighlight onPress={() => { }} key={index} style={styles.storeRow}>
            <Text style={styles.storeText}>{store.name.toUpperCase()}</Text>
          </TouchableHighlight>
        )
      })
    }
  }
```

**Comment by ashusdn** [comment] 2017-09-18 10:33
HelloTeam,

I am facing the same issue when I try to onPress method inside _renderHeader it will show function not defined. 


    _renderHeader(section, i, isActive) {
        return (
             <View style={styles.headerRowStyle}>
                    <Image style={styles.carretImageStyle} source={isActive ? caretDown : caret} />
                    <Text style={styles.headerText}>{section.title}</Text>
                    <TouchableOpacity  onPress={() => onUnitItemClick(section.title)}   underlayColor="transparent">
                        <Image source={arrow} />
                    </TouchableOpacity>
                </View>
      );
    }

Can you please provide some solution regarding this.

**Comment by Sonukr** [comment] 2017-09-21 06:47
I am Facing the same issue, I tried with both method i.e. putting that function inside render method and outside of render method but it is showing the same error.  any solution for this?

**Comment by jas823** [comment] 2017-10-16 06:57
I encountered this problem also. I tried the solution given by @rdoyle975, it still didn't work, but it was close, the idea of "inserting the function inside.." was the clue. So thanks :) I figured that the problem was due to the Component's instance aren't passed to the function inside the Accordion and thus showing the undefined error. The key of the solution is to place _renderContent function inside the render() function in order to have access to "this". The following is what I ended up with (you'll need to remove the comments in the return part to make it work): 

```
  onChangeScreen(screen, section) {
    const { navigation } = this.props;
    navigation.navigate(screen, { data: section });
  }

  render() {
    _renderContent = section => {
      return (
        <View>
          <TouchableOpacity onPress={() => this.onChangeScreen("DetailsScreen", section)}>
            <Text>Details</Text>
          </TouchableOpacity>
        </View>
      );
     };
    
     return (
      <ScrollView style={styles.container}>
        <KeyboardAvoidingView behavior="position">
          <Accordion
            sections={dataList}
            renderHeader={this._renderHeader} //_renderHeader is outside of render() and has no access to "this"
            renderContent={_renderContent} //this function call is what works for me
            easing="easeOutCubic"
          />
        </KeyboardAvoidingView>
      </ScrollView>
    );
  }
````

**Comment by swapkids** [comment] 2017-10-30 21:25
You need to bind `this` to the function by eg. use ES6 lambda functions

`_renderContent = (section) => { ... } `

instead of

`_renderContent(section) { ... }`

that should do the trick

**Comment by iRoachie** [comment] 2018-01-01 19:15
Closing this as solved, as it really isn't with the library. Be sure to use an arrow function on the `renderContent` and `renderHeader` methods to preserve access to the class scope

**Closed by iRoachie** 2018-01-01 19:15 UTC
Labels: help wanted

**Comment by sohanpatil44** [comment] 2018-02-19 08:22
Call a function on onPress of TouchableOpacity inside renderheader function of react-native-accordion
shwing error:undefined is not a function

**Comment by AfanasievN** [comment] 2019-09-19 15:45
@jas823 thanks! it worked!

**Comment by arunachalalam** [comment] 2020-03-30 13:34
Thanks a ton  Swapkids You need to bind this to the function by eg. use ES6 lambda functions

_renderContent = (section) => { ... }

instead of

_renderContent(section) { ... }

helped me
