### ISSUE TITLE
After setting up activeSection, other options can not be opened, and the current option cannot be closed.

### ISSUE THREAD

**Issue by kmlidc** [oblador/react-native-collapsible#226] opened 2018-07-26 09:29 UTC
设置了 activeSection 后，无法打开其他选项，也无法关闭当前选项

After setting up activeSection, other options can not be opened, and the current option cannot be closed.

**Comment by maikmacs** [comment] 2018-08-21 15:12
I have the same issue and get solvet with this https://github.com/oblador/react-native-collapsible/issues/139

**Comment by maikmacs** [comment] 2018-08-21 15:13
I had the same problem and I could solve it with this https://github.com/oblador/react-native-collapsible/issues/139

**Comment by iRoachie** [comment] 2018-08-21 16:06
Closing as duplicate of #139

**Closed by iRoachie** 2018-08-21 16:06 UTC
